/** Tokens de injeção de dependência do módulo Vehicles (Repository Pattern, Dossiê 12 Seção 6.1). */
export const VEHICLE_REPOSITORY = Symbol("VEHICLE_REPOSITORY");
export const VEHICLE_DOCUMENT_REPOSITORY = Symbol("VEHICLE_DOCUMENT_REPOSITORY");
export const VEHICLE_MAINTENANCE_REPOSITORY = Symbol("VEHICLE_MAINTENANCE_REPOSITORY");
export const VEHICLE_REMINDER_REPOSITORY = Symbol("VEHICLE_REMINDER_REPOSITORY");
export const VEHICLE_ASSIGNMENT_REPOSITORY = Symbol("VEHICLE_ASSIGNMENT_REPOSITORY");
export const VEHICLE_CHECKLIST_REPOSITORY = Symbol("VEHICLE_CHECKLIST_REPOSITORY");
export const VEHICLE_OCCURRENCE_REPOSITORY = Symbol("VEHICLE_OCCURRENCE_REPOSITORY");
